# Generated by Django 4.1.7 on 2023-02-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=200)),
                ("code_company", models.CharField(max_length=8, unique=True)),
                ("director", models.CharField(max_length=255)),
                ("short_dir_name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("bank_account", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                ("mfo", models.CharField(max_length=255)),
                ("date_generate", models.CharField(max_length=255)),
            ],
        ),
    ]
